### ISSUE TITLE
How do you use this plugin?

### ISSUE THREAD

**Issue by ghost** [andremartinssw/docusaurus-plugin-showcase#1]
Hey @andremartinssw! Love that you made this plugin — exactly what I was hoping to find.

I'm having trouble using it though. I installed it and added the `plugins` line to my config file, but I'm getting:

```
[ERROR] Error: ENOENT: no such file or directory, open '.../src/data/articles.json'
```

There are no other instructions on the readme, so I'm not sure how to proceed. I'm assuming I have to copy your project structure somehow (?) but I don't know what all the files do.

Could you help here? Thanks!

**Comment by andremartinssw** [comment]
Hi @certainlyNotHeisenberg :)

I've decided to make the plugin a local one (instead of one you can install from npm), and have updated the [README](https://github.com/andremartinssw/docusaurus-plugin-showcase/blob/main/README.md) with new instructions on how to to use it.

I've fixed the error you mentioned by checking for the existence of `src/data` before proceeding with adding the `articles.json` file. That file is what the plugin uses to populate the showcase.

Let me know if you run into any issues following the latest instructions!
